#!/bin/sh

uci set network.tap0=interface
uci set network.tap0.proto=none
uci set network.tap0.ifname=tap0
uci set network.tap1=interface
uci set network.tap1.proto=none
uci set network.tap1.ifname=tap1

uci commit network

uci set olsrd.tap0=Interface
uci set olsrd.tap0.ignore=0
uci set olsrd.tap0.interface=tap0
uci set olsrd.tap0.Mode=mesh
uci set olsrd.tap1=Interface
uci set olsrd.tap1.ignore=0
uci set olsrd.tap1.interface=tap1
uci set olsrd.tap1.Mode=mesh

uci commit olsrd

chmod 600 /etc/openvpn/halle.key

